apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod1
  name: pod1
spec:
  volumes:
    - name: v1
      hostPath:
        path: /etc/hosts
  containers:
  - image: nginx
    name: c1
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /data/hosts
        name: v1
  dnsPolicy: ClusterFirst
  restartPolicy: Always