apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod2
  name: pod2
spec:
  containers:
  - image: nginx
    name: pod1
    resources: {}
    command:
      - sh
      - -c
      - sheep 1d
  dnsPolicy: ClusterFirst
  restartPolicy: Always